---
title: "clean gender and age"
author: "YI LIU"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r}
suicide_rate_df = 
  read_excel("./suicide_age_gender.xlsx") %>% 
  janitor::clean_names() %>%
  filter(year == 2017) %>% 
  filter(is.na(ten_year_age_groups)) %>% 
  drop_na(gender) %>% 
  select(state,gender, deaths, population) %>%
  group_by(state) %>% 
  summarize(
    suicide_rate_per100000 = sum(deaths)*100000/sum(population)
  )

write_csv(suicide_rate_df,"./Suicide_rate_2017.csv")
write_csv(suicide_rate_df,"../data/Suicide_rate_2017.csv")
```

```{r}
gender_rate_df = 
  read_excel("./suicide_age_gender.xlsx") %>% 
  janitor::clean_names() %>%
  filter(year == 2017) %>% 
  filter(is.na(ten_year_age_groups)) %>% 
  drop_na(gender) %>% 
  select(state,gender,population) %>% 
  pivot_wider(
    names_from = "gender",
    values_from = "population"
  ) %>% 
  mutate(
    female_ratio = Female/(Female+Male),
    male_ratio = Male/(Female+Male)
  ) %>% 
  select(state, female_ratio, male_ratio)
write_csv(gender_rate_df,"./Gender_rate_2017.csv")
write_csv(gender_rate_df,"../data/Gender_rate_2017.csv")
```

```{r}
gender_suiciderate_df =
  read_excel("./suicide_age_gender.xlsx") %>% 
  janitor::clean_names() %>%
  filter(year == 2017) %>% 
  filter(is.na(ten_year_age_groups)) %>% 
  drop_na(gender) %>% 
  select(state,gender,deaths,population) %>% 
  mutate(
    suicide_rate_per100000 = deaths*100000/population
  ) %>% 
  select(state, gender, suicide_rate_per100000)

write_csv(gender_suiciderate_df,"./Gender_suiciderate_2017.csv")
write_csv(gender_suiciderate_df,"../data/Gender_suiciderate_2017.csv")

```


```{r}
age_df =
  read_excel("./suicide_age_gender.xlsx") %>% 
  janitor::clean_names() %>%
  filter(year == 2017) %>% 
  drop_na(ten_year_age_groups) %>% 
  select(state,gender,ten_year_age_groups, population) %>% 
  pivot_wider(
    names_from = "gender",
    values_from = "population"
  ) %>% 
  mutate(
    Female = replace(Female, is.na(Female), 0),
    Male = replace(Male, is.na(Male), 0),
    total = Female + Male
  ) %>% 
  select(-Female, -Male) %>%
 pivot_wider(
    names_from = "ten_year_age_groups",
    values_from = "total"
  ) %>%
  rename("Y15_24" = "15-24 years", "Y25_34" = "25-34 years","Y35_44" = "35-44 years","Y45_54" = "45-54 years","Y55_64" = "55-64 years","Y65_74" = "65-74 years","Y5_14" = "5-14 years", "Y75_84" = "75-84 years","Y85_larger" = "85+ years") %>% 
  mutate(
    Y5_14 = replace(Y5_14, is.na(Y5_14), 0),
    Y15_24 = replace(Y15_24, is.na(Y15_24), 0),
    Y25_34 = replace(Y25_34, is.na(Y25_34), 0),
    Y35_44 = replace(Y35_44, is.na(Y35_44), 0),
    Y45_54 = replace(Y45_54, is.na(Y45_54), 0),
    Y55_64 = replace(Y55_64, is.na(Y55_64), 0),
    Y65_74 = replace(Y65_74, is.na(Y65_74), 0),
    Y75_84 = replace(Y75_84, is.na(Y75_84), 0),
    Y85_larger = replace(Y85_larger, is.na(Y85_larger), 0),
    total = Y5_14 + Y15_24 + Y25_34+Y35_44+Y45_54+Y55_64+Y65_74 +Y75_84+Y85_larger,
    R5_14 = Y5_14/total,
    R15_24= Y15_24/total,
    R25_34=Y25_34/total,
    R35_44=Y35_44/total,
    R45_54=Y45_54/total,
    R55_64=Y55_64/total,
    R65_74=Y65_74/total,
    R75_84=Y75_84/total,
    R85_larger = Y85_larger/total
  ) %>% 
  select(state, contains("R"))

write_csv(age_df,"./Agerate_2017.csv")
write_csv(age_df,"../data/Agerate_2017.csv")

```

